#!/bin/bash

echo "TEAM AA"
echo "12 January 2017"
echo "Calculate LandSat NDVI"


fn="../data/LE71700552001036SGS00_SR_Gewata_INT1U.tif"

echo "The input file: $fn"

outfn="../data/ndvi.tif"

echo "The output file: $outfn"

echo "calculate ndvi"

gdal_calc.py -A $fn --A_band=4 -B $fn --B_band=3 --outfile=$outfn --calc="(A.astype(float)-B)/(A.astype(float)+B)" --type='Float32'

echo "The output file of the resampled NDVI"

outfn2="../data/ndvi_resampled.tif"

gdalwarp -ts 60 60 -r cubic $outfn $outfn2

echo "The output of the reprojected New NDVI"

outfn3="../data/reprojected_resample_NDVI"

gdalwarp -t_srs "EPSG:4326" $outfn2 $outfn3


